// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment.grpc.proto;

public interface QueryIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint64 identificationNumber = 1;</code>
   * @return The identificationNumber.
   */
  long getIdentificationNumber();
}
