// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment.grpc.proto;

/**
 * Protobuf type {@code ResponseIds}
 */
public final class ResponseIds extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ResponseIds)
    ResponseIdsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseIds.newBuilder() to construct.
  private ResponseIds(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseIds() {
    identificationNumber_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResponseIds();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseIds(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              identificationNumber_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            identificationNumber_.addLong(input.readSInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              identificationNumber_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              identificationNumber_.addLong(input.readSInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        identificationNumber_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.sdj3.assignment.grpc.proto.Slaughterhouse.internal_static_ResponseIds_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.sdj3.assignment.grpc.proto.Slaughterhouse.internal_static_ResponseIds_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.sdj3.assignment.grpc.proto.ResponseIds.class, dk.via.sdj3.assignment.grpc.proto.ResponseIds.Builder.class);
  }

  public static final int IDENTIFICATIONNUMBER_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.LongList identificationNumber_;
  /**
   * <code>repeated sint64 identificationNumber = 1;</code>
   * @return A list containing the identificationNumber.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getIdentificationNumberList() {
    return identificationNumber_;
  }
  /**
   * <code>repeated sint64 identificationNumber = 1;</code>
   * @return The count of identificationNumber.
   */
  public int getIdentificationNumberCount() {
    return identificationNumber_.size();
  }
  /**
   * <code>repeated sint64 identificationNumber = 1;</code>
   * @param index The index of the element to return.
   * @return The identificationNumber at the given index.
   */
  public long getIdentificationNumber(int index) {
    return identificationNumber_.getLong(index);
  }
  private int identificationNumberMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getIdentificationNumberList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(identificationNumberMemoizedSerializedSize);
    }
    for (int i = 0; i < identificationNumber_.size(); i++) {
      output.writeSInt64NoTag(identificationNumber_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < identificationNumber_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeSInt64SizeNoTag(identificationNumber_.getLong(i));
      }
      size += dataSize;
      if (!getIdentificationNumberList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      identificationNumberMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.sdj3.assignment.grpc.proto.ResponseIds)) {
      return super.equals(obj);
    }
    dk.via.sdj3.assignment.grpc.proto.ResponseIds other = (dk.via.sdj3.assignment.grpc.proto.ResponseIds) obj;

    if (!getIdentificationNumberList()
        .equals(other.getIdentificationNumberList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIdentificationNumberCount() > 0) {
      hash = (37 * hash) + IDENTIFICATIONNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentificationNumberList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.sdj3.assignment.grpc.proto.ResponseIds prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ResponseIds}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ResponseIds)
      dk.via.sdj3.assignment.grpc.proto.ResponseIdsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.sdj3.assignment.grpc.proto.Slaughterhouse.internal_static_ResponseIds_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.sdj3.assignment.grpc.proto.Slaughterhouse.internal_static_ResponseIds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.sdj3.assignment.grpc.proto.ResponseIds.class, dk.via.sdj3.assignment.grpc.proto.ResponseIds.Builder.class);
    }

    // Construct using dk.via.sdj3.assignment.grpc.proto.ResponseIds.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      identificationNumber_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.sdj3.assignment.grpc.proto.Slaughterhouse.internal_static_ResponseIds_descriptor;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.grpc.proto.ResponseIds getDefaultInstanceForType() {
      return dk.via.sdj3.assignment.grpc.proto.ResponseIds.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.grpc.proto.ResponseIds build() {
      dk.via.sdj3.assignment.grpc.proto.ResponseIds result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.grpc.proto.ResponseIds buildPartial() {
      dk.via.sdj3.assignment.grpc.proto.ResponseIds result = new dk.via.sdj3.assignment.grpc.proto.ResponseIds(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        identificationNumber_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.identificationNumber_ = identificationNumber_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.sdj3.assignment.grpc.proto.ResponseIds) {
        return mergeFrom((dk.via.sdj3.assignment.grpc.proto.ResponseIds)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.sdj3.assignment.grpc.proto.ResponseIds other) {
      if (other == dk.via.sdj3.assignment.grpc.proto.ResponseIds.getDefaultInstance()) return this;
      if (!other.identificationNumber_.isEmpty()) {
        if (identificationNumber_.isEmpty()) {
          identificationNumber_ = other.identificationNumber_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureIdentificationNumberIsMutable();
          identificationNumber_.addAll(other.identificationNumber_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.sdj3.assignment.grpc.proto.ResponseIds parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.sdj3.assignment.grpc.proto.ResponseIds) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList identificationNumber_ = emptyLongList();
    private void ensureIdentificationNumberIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        identificationNumber_ = mutableCopy(identificationNumber_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated sint64 identificationNumber = 1;</code>
     * @return A list containing the identificationNumber.
     */
    public java.util.List<java.lang.Long>
        getIdentificationNumberList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(identificationNumber_) : identificationNumber_;
    }
    /**
     * <code>repeated sint64 identificationNumber = 1;</code>
     * @return The count of identificationNumber.
     */
    public int getIdentificationNumberCount() {
      return identificationNumber_.size();
    }
    /**
     * <code>repeated sint64 identificationNumber = 1;</code>
     * @param index The index of the element to return.
     * @return The identificationNumber at the given index.
     */
    public long getIdentificationNumber(int index) {
      return identificationNumber_.getLong(index);
    }
    /**
     * <code>repeated sint64 identificationNumber = 1;</code>
     * @param index The index to set the value at.
     * @param value The identificationNumber to set.
     * @return This builder for chaining.
     */
    public Builder setIdentificationNumber(
        int index, long value) {
      ensureIdentificationNumberIsMutable();
      identificationNumber_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint64 identificationNumber = 1;</code>
     * @param value The identificationNumber to add.
     * @return This builder for chaining.
     */
    public Builder addIdentificationNumber(long value) {
      ensureIdentificationNumberIsMutable();
      identificationNumber_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint64 identificationNumber = 1;</code>
     * @param values The identificationNumber to add.
     * @return This builder for chaining.
     */
    public Builder addAllIdentificationNumber(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureIdentificationNumberIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, identificationNumber_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint64 identificationNumber = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentificationNumber() {
      identificationNumber_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ResponseIds)
  }

  // @@protoc_insertion_point(class_scope:ResponseIds)
  private static final dk.via.sdj3.assignment.grpc.proto.ResponseIds DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.sdj3.assignment.grpc.proto.ResponseIds();
  }

  public static dk.via.sdj3.assignment.grpc.proto.ResponseIds getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseIds>
      PARSER = new com.google.protobuf.AbstractParser<ResponseIds>() {
    @java.lang.Override
    public ResponseIds parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseIds(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseIds> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseIds> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.sdj3.assignment.grpc.proto.ResponseIds getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

