// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment.grpc.proto;

public interface ResponseIdsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseIds)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated sint64 identificationNumber = 1;</code>
   * @return A list containing the identificationNumber.
   */
  java.util.List<java.lang.Long> getIdentificationNumberList();
  /**
   * <code>repeated sint64 identificationNumber = 1;</code>
   * @return The count of identificationNumber.
   */
  int getIdentificationNumberCount();
  /**
   * <code>repeated sint64 identificationNumber = 1;</code>
   * @param index The index of the element to return.
   * @return The identificationNumber at the given index.
   */
  long getIdentificationNumber(int index);
}
