// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment.grpc.proto;

public final class Slaughterhouse {
  private Slaughterhouse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseIds_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseIds_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024slaughterhouse.proto\"\'\n\007QueryId\022\034\n\024ide" +
      "ntificationNumber\030\001 \001(\022\"+\n\013ResponseIds\022\034" +
      "\n\024identificationNumber\030\001 \003(\0222n\n\025Slaughte" +
      "rhouseService\022)\n\rgetAnimalsFor\022\010.QueryId" +
      "\032\014.ResponseIds\"\000\022*\n\016getProductsFor\022\010.Que" +
      "ryId\032\014.ResponseIds\"\000B%\n!dk.via.sdj3.assi" +
      "gnment.grpc.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_QueryId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryId_descriptor,
        new java.lang.String[] { "IdentificationNumber", });
    internal_static_ResponseIds_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseIds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseIds_descriptor,
        new java.lang.String[] { "IdentificationNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
