// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment;

/**
 * <pre>
 * for code?
 * </pre>
 *
 * Protobuf type {@code slaughterhouse.Animal}
 */
public final class Animal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:slaughterhouse.Animal)
    AnimalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Animal.newBuilder() to construct.
  private Animal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Animal() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Animal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Animal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            registrationId_ = input.readInt32();
            break;
          }
          case 18: {
            dk.via.sdj3.assignment.Product.Builder subBuilder = null;
            if (productId_ != null) {
              subBuilder = productId_.toBuilder();
            }
            productId_ = input.readMessage(dk.via.sdj3.assignment.Product.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(productId_);
              productId_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Animal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Animal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.sdj3.assignment.Animal.class, dk.via.sdj3.assignment.Animal.Builder.class);
  }

  public static final int REGISTRATION_ID_FIELD_NUMBER = 1;
  private int registrationId_;
  /**
   * <code>int32 registration_id = 1;</code>
   * @return The registrationId.
   */
  @java.lang.Override
  public int getRegistrationId() {
    return registrationId_;
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 2;
  private dk.via.sdj3.assignment.Product productId_;
  /**
   * <code>.slaughterhouse.Product product_id = 2;</code>
   * @return Whether the productId field is set.
   */
  @java.lang.Override
  public boolean hasProductId() {
    return productId_ != null;
  }
  /**
   * <code>.slaughterhouse.Product product_id = 2;</code>
   * @return The productId.
   */
  @java.lang.Override
  public dk.via.sdj3.assignment.Product getProductId() {
    return productId_ == null ? dk.via.sdj3.assignment.Product.getDefaultInstance() : productId_;
  }
  /**
   * <code>.slaughterhouse.Product product_id = 2;</code>
   */
  @java.lang.Override
  public dk.via.sdj3.assignment.ProductOrBuilder getProductIdOrBuilder() {
    return getProductId();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (registrationId_ != 0) {
      output.writeInt32(1, registrationId_);
    }
    if (productId_ != null) {
      output.writeMessage(2, getProductId());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (registrationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, registrationId_);
    }
    if (productId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getProductId());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.sdj3.assignment.Animal)) {
      return super.equals(obj);
    }
    dk.via.sdj3.assignment.Animal other = (dk.via.sdj3.assignment.Animal) obj;

    if (getRegistrationId()
        != other.getRegistrationId()) return false;
    if (hasProductId() != other.hasProductId()) return false;
    if (hasProductId()) {
      if (!getProductId()
          .equals(other.getProductId())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REGISTRATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRegistrationId();
    if (hasProductId()) {
      hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.sdj3.assignment.Animal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.Animal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Animal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.Animal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Animal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.Animal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Animal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.Animal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Animal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.Animal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Animal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.Animal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.sdj3.assignment.Animal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * for code?
   * </pre>
   *
   * Protobuf type {@code slaughterhouse.Animal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:slaughterhouse.Animal)
      dk.via.sdj3.assignment.AnimalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Animal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Animal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.sdj3.assignment.Animal.class, dk.via.sdj3.assignment.Animal.Builder.class);
    }

    // Construct using dk.via.sdj3.assignment.Animal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      registrationId_ = 0;

      if (productIdBuilder_ == null) {
        productId_ = null;
      } else {
        productId_ = null;
        productIdBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Animal_descriptor;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.Animal getDefaultInstanceForType() {
      return dk.via.sdj3.assignment.Animal.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.Animal build() {
      dk.via.sdj3.assignment.Animal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.Animal buildPartial() {
      dk.via.sdj3.assignment.Animal result = new dk.via.sdj3.assignment.Animal(this);
      result.registrationId_ = registrationId_;
      if (productIdBuilder_ == null) {
        result.productId_ = productId_;
      } else {
        result.productId_ = productIdBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.sdj3.assignment.Animal) {
        return mergeFrom((dk.via.sdj3.assignment.Animal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.sdj3.assignment.Animal other) {
      if (other == dk.via.sdj3.assignment.Animal.getDefaultInstance()) return this;
      if (other.getRegistrationId() != 0) {
        setRegistrationId(other.getRegistrationId());
      }
      if (other.hasProductId()) {
        mergeProductId(other.getProductId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.sdj3.assignment.Animal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.sdj3.assignment.Animal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int registrationId_ ;
    /**
     * <code>int32 registration_id = 1;</code>
     * @return The registrationId.
     */
    @java.lang.Override
    public int getRegistrationId() {
      return registrationId_;
    }
    /**
     * <code>int32 registration_id = 1;</code>
     * @param value The registrationId to set.
     * @return This builder for chaining.
     */
    public Builder setRegistrationId(int value) {
      
      registrationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 registration_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistrationId() {
      
      registrationId_ = 0;
      onChanged();
      return this;
    }

    private dk.via.sdj3.assignment.Product productId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.sdj3.assignment.Product, dk.via.sdj3.assignment.Product.Builder, dk.via.sdj3.assignment.ProductOrBuilder> productIdBuilder_;
    /**
     * <code>.slaughterhouse.Product product_id = 2;</code>
     * @return Whether the productId field is set.
     */
    public boolean hasProductId() {
      return productIdBuilder_ != null || productId_ != null;
    }
    /**
     * <code>.slaughterhouse.Product product_id = 2;</code>
     * @return The productId.
     */
    public dk.via.sdj3.assignment.Product getProductId() {
      if (productIdBuilder_ == null) {
        return productId_ == null ? dk.via.sdj3.assignment.Product.getDefaultInstance() : productId_;
      } else {
        return productIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.slaughterhouse.Product product_id = 2;</code>
     */
    public Builder setProductId(dk.via.sdj3.assignment.Product value) {
      if (productIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        productId_ = value;
        onChanged();
      } else {
        productIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.Product product_id = 2;</code>
     */
    public Builder setProductId(
        dk.via.sdj3.assignment.Product.Builder builderForValue) {
      if (productIdBuilder_ == null) {
        productId_ = builderForValue.build();
        onChanged();
      } else {
        productIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.Product product_id = 2;</code>
     */
    public Builder mergeProductId(dk.via.sdj3.assignment.Product value) {
      if (productIdBuilder_ == null) {
        if (productId_ != null) {
          productId_ =
            dk.via.sdj3.assignment.Product.newBuilder(productId_).mergeFrom(value).buildPartial();
        } else {
          productId_ = value;
        }
        onChanged();
      } else {
        productIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.Product product_id = 2;</code>
     */
    public Builder clearProductId() {
      if (productIdBuilder_ == null) {
        productId_ = null;
        onChanged();
      } else {
        productId_ = null;
        productIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.Product product_id = 2;</code>
     */
    public dk.via.sdj3.assignment.Product.Builder getProductIdBuilder() {
      
      onChanged();
      return getProductIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.slaughterhouse.Product product_id = 2;</code>
     */
    public dk.via.sdj3.assignment.ProductOrBuilder getProductIdOrBuilder() {
      if (productIdBuilder_ != null) {
        return productIdBuilder_.getMessageOrBuilder();
      } else {
        return productId_ == null ?
            dk.via.sdj3.assignment.Product.getDefaultInstance() : productId_;
      }
    }
    /**
     * <code>.slaughterhouse.Product product_id = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.sdj3.assignment.Product, dk.via.sdj3.assignment.Product.Builder, dk.via.sdj3.assignment.ProductOrBuilder> 
        getProductIdFieldBuilder() {
      if (productIdBuilder_ == null) {
        productIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.sdj3.assignment.Product, dk.via.sdj3.assignment.Product.Builder, dk.via.sdj3.assignment.ProductOrBuilder>(
                getProductId(),
                getParentForChildren(),
                isClean());
        productId_ = null;
      }
      return productIdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:slaughterhouse.Animal)
  }

  // @@protoc_insertion_point(class_scope:slaughterhouse.Animal)
  private static final dk.via.sdj3.assignment.Animal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.sdj3.assignment.Animal();
  }

  public static dk.via.sdj3.assignment.Animal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Animal>
      PARSER = new com.google.protobuf.AbstractParser<Animal>() {
    @java.lang.Override
    public Animal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Animal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Animal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Animal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.sdj3.assignment.Animal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

