// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment;

public interface AnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.Animal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 registration_id = 1;</code>
   * @return The registrationId.
   */
  int getRegistrationId();

  /**
   * <code>.slaughterhouse.Product product_id = 2;</code>
   * @return Whether the productId field is set.
   */
  boolean hasProductId();
  /**
   * <code>.slaughterhouse.Product product_id = 2;</code>
   * @return The productId.
   */
  dk.via.sdj3.assignment.Product getProductId();
  /**
   * <code>.slaughterhouse.Product product_id = 2;</code>
   */
  dk.via.sdj3.assignment.ProductOrBuilder getProductIdOrBuilder();
}
