// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment;

/**
 * Protobuf type {@code slaughterhouse.AnimalList}
 */
public final class AnimalList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:slaughterhouse.AnimalList)
    AnimalListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnimalList.newBuilder() to construct.
  private AnimalList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnimalList() {
    animalId_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnimalList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnimalList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              animalId_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            animalId_.addInt(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              animalId_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              animalId_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        animalId_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_AnimalList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_AnimalList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.sdj3.assignment.AnimalList.class, dk.via.sdj3.assignment.AnimalList.Builder.class);
  }

  public static final int ANIMAL_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList animalId_;
  /**
   * <code>repeated int32 animal_id = 1;</code>
   * @return A list containing the animalId.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getAnimalIdList() {
    return animalId_;
  }
  /**
   * <code>repeated int32 animal_id = 1;</code>
   * @return The count of animalId.
   */
  public int getAnimalIdCount() {
    return animalId_.size();
  }
  /**
   * <code>repeated int32 animal_id = 1;</code>
   * @param index The index of the element to return.
   * @return The animalId at the given index.
   */
  public int getAnimalId(int index) {
    return animalId_.getInt(index);
  }
  private int animalIdMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getAnimalIdList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(animalIdMemoizedSerializedSize);
    }
    for (int i = 0; i < animalId_.size(); i++) {
      output.writeInt32NoTag(animalId_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < animalId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(animalId_.getInt(i));
      }
      size += dataSize;
      if (!getAnimalIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      animalIdMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.sdj3.assignment.AnimalList)) {
      return super.equals(obj);
    }
    dk.via.sdj3.assignment.AnimalList other = (dk.via.sdj3.assignment.AnimalList) obj;

    if (!getAnimalIdList()
        .equals(other.getAnimalIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAnimalIdCount() > 0) {
      hash = (37 * hash) + ANIMAL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.sdj3.assignment.AnimalList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.AnimalList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.AnimalList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.AnimalList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.AnimalList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.AnimalList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.AnimalList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.AnimalList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.AnimalList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.AnimalList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.AnimalList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.AnimalList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.sdj3.assignment.AnimalList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code slaughterhouse.AnimalList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:slaughterhouse.AnimalList)
      dk.via.sdj3.assignment.AnimalListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_AnimalList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_AnimalList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.sdj3.assignment.AnimalList.class, dk.via.sdj3.assignment.AnimalList.Builder.class);
    }

    // Construct using dk.via.sdj3.assignment.AnimalList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      animalId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_AnimalList_descriptor;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.AnimalList getDefaultInstanceForType() {
      return dk.via.sdj3.assignment.AnimalList.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.AnimalList build() {
      dk.via.sdj3.assignment.AnimalList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.AnimalList buildPartial() {
      dk.via.sdj3.assignment.AnimalList result = new dk.via.sdj3.assignment.AnimalList(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        animalId_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.animalId_ = animalId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.sdj3.assignment.AnimalList) {
        return mergeFrom((dk.via.sdj3.assignment.AnimalList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.sdj3.assignment.AnimalList other) {
      if (other == dk.via.sdj3.assignment.AnimalList.getDefaultInstance()) return this;
      if (!other.animalId_.isEmpty()) {
        if (animalId_.isEmpty()) {
          animalId_ = other.animalId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAnimalIdIsMutable();
          animalId_.addAll(other.animalId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.sdj3.assignment.AnimalList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.sdj3.assignment.AnimalList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList animalId_ = emptyIntList();
    private void ensureAnimalIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        animalId_ = mutableCopy(animalId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 animal_id = 1;</code>
     * @return A list containing the animalId.
     */
    public java.util.List<java.lang.Integer>
        getAnimalIdList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(animalId_) : animalId_;
    }
    /**
     * <code>repeated int32 animal_id = 1;</code>
     * @return The count of animalId.
     */
    public int getAnimalIdCount() {
      return animalId_.size();
    }
    /**
     * <code>repeated int32 animal_id = 1;</code>
     * @param index The index of the element to return.
     * @return The animalId at the given index.
     */
    public int getAnimalId(int index) {
      return animalId_.getInt(index);
    }
    /**
     * <code>repeated int32 animal_id = 1;</code>
     * @param index The index to set the value at.
     * @param value The animalId to set.
     * @return This builder for chaining.
     */
    public Builder setAnimalId(
        int index, int value) {
      ensureAnimalIdIsMutable();
      animalId_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 animal_id = 1;</code>
     * @param value The animalId to add.
     * @return This builder for chaining.
     */
    public Builder addAnimalId(int value) {
      ensureAnimalIdIsMutable();
      animalId_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 animal_id = 1;</code>
     * @param values The animalId to add.
     * @return This builder for chaining.
     */
    public Builder addAllAnimalId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureAnimalIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, animalId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 animal_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnimalId() {
      animalId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:slaughterhouse.AnimalList)
  }

  // @@protoc_insertion_point(class_scope:slaughterhouse.AnimalList)
  private static final dk.via.sdj3.assignment.AnimalList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.sdj3.assignment.AnimalList();
  }

  public static dk.via.sdj3.assignment.AnimalList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnimalList>
      PARSER = new com.google.protobuf.AbstractParser<AnimalList>() {
    @java.lang.Override
    public AnimalList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnimalList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnimalList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnimalList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.sdj3.assignment.AnimalList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

