// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment;

public interface AnimalListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.AnimalList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 animal_id = 1;</code>
   * @return A list containing the animalId.
   */
  java.util.List<java.lang.Integer> getAnimalIdList();
  /**
   * <code>repeated int32 animal_id = 1;</code>
   * @return The count of animalId.
   */
  int getAnimalIdCount();
  /**
   * <code>repeated int32 animal_id = 1;</code>
   * @param index The index of the element to return.
   * @return The animalId at the given index.
   */
  int getAnimalId(int index);
}
