// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment;

/**
 * Protobuf type {@code slaughterhouse.ProductsList}
 */
public final class ProductsList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:slaughterhouse.ProductsList)
    ProductsListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductsList.newBuilder() to construct.
  private ProductsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductsList() {
    productId_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductsList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductsList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              productId_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            productId_.addInt(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              productId_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              productId_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        productId_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_ProductsList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_ProductsList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.sdj3.assignment.ProductsList.class, dk.via.sdj3.assignment.ProductsList.Builder.class);
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList productId_;
  /**
   * <code>repeated int32 product_id = 1;</code>
   * @return A list containing the productId.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getProductIdList() {
    return productId_;
  }
  /**
   * <code>repeated int32 product_id = 1;</code>
   * @return The count of productId.
   */
  public int getProductIdCount() {
    return productId_.size();
  }
  /**
   * <code>repeated int32 product_id = 1;</code>
   * @param index The index of the element to return.
   * @return The productId at the given index.
   */
  public int getProductId(int index) {
    return productId_.getInt(index);
  }
  private int productIdMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getProductIdList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(productIdMemoizedSerializedSize);
    }
    for (int i = 0; i < productId_.size(); i++) {
      output.writeInt32NoTag(productId_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < productId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(productId_.getInt(i));
      }
      size += dataSize;
      if (!getProductIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      productIdMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.sdj3.assignment.ProductsList)) {
      return super.equals(obj);
    }
    dk.via.sdj3.assignment.ProductsList other = (dk.via.sdj3.assignment.ProductsList) obj;

    if (!getProductIdList()
        .equals(other.getProductIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProductIdCount() > 0) {
      hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getProductIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.sdj3.assignment.ProductsList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.ProductsList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.ProductsList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.ProductsList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.ProductsList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.ProductsList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.ProductsList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.ProductsList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.ProductsList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.ProductsList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.ProductsList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.ProductsList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.sdj3.assignment.ProductsList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code slaughterhouse.ProductsList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:slaughterhouse.ProductsList)
      dk.via.sdj3.assignment.ProductsListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_ProductsList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_ProductsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.sdj3.assignment.ProductsList.class, dk.via.sdj3.assignment.ProductsList.Builder.class);
    }

    // Construct using dk.via.sdj3.assignment.ProductsList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      productId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_ProductsList_descriptor;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.ProductsList getDefaultInstanceForType() {
      return dk.via.sdj3.assignment.ProductsList.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.ProductsList build() {
      dk.via.sdj3.assignment.ProductsList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.ProductsList buildPartial() {
      dk.via.sdj3.assignment.ProductsList result = new dk.via.sdj3.assignment.ProductsList(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        productId_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.productId_ = productId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.sdj3.assignment.ProductsList) {
        return mergeFrom((dk.via.sdj3.assignment.ProductsList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.sdj3.assignment.ProductsList other) {
      if (other == dk.via.sdj3.assignment.ProductsList.getDefaultInstance()) return this;
      if (!other.productId_.isEmpty()) {
        if (productId_.isEmpty()) {
          productId_ = other.productId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureProductIdIsMutable();
          productId_.addAll(other.productId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.sdj3.assignment.ProductsList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.sdj3.assignment.ProductsList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList productId_ = emptyIntList();
    private void ensureProductIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        productId_ = mutableCopy(productId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 product_id = 1;</code>
     * @return A list containing the productId.
     */
    public java.util.List<java.lang.Integer>
        getProductIdList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(productId_) : productId_;
    }
    /**
     * <code>repeated int32 product_id = 1;</code>
     * @return The count of productId.
     */
    public int getProductIdCount() {
      return productId_.size();
    }
    /**
     * <code>repeated int32 product_id = 1;</code>
     * @param index The index of the element to return.
     * @return The productId at the given index.
     */
    public int getProductId(int index) {
      return productId_.getInt(index);
    }
    /**
     * <code>repeated int32 product_id = 1;</code>
     * @param index The index to set the value at.
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(
        int index, int value) {
      ensureProductIdIsMutable();
      productId_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 product_id = 1;</code>
     * @param value The productId to add.
     * @return This builder for chaining.
     */
    public Builder addProductId(int value) {
      ensureProductIdIsMutable();
      productId_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 product_id = 1;</code>
     * @param values The productId to add.
     * @return This builder for chaining.
     */
    public Builder addAllProductId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureProductIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, productId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 product_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      productId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:slaughterhouse.ProductsList)
  }

  // @@protoc_insertion_point(class_scope:slaughterhouse.ProductsList)
  private static final dk.via.sdj3.assignment.ProductsList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.sdj3.assignment.ProductsList();
  }

  public static dk.via.sdj3.assignment.ProductsList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductsList>
      PARSER = new com.google.protobuf.AbstractParser<ProductsList>() {
    @java.lang.Override
    public ProductsList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductsList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductsList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductsList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.sdj3.assignment.ProductsList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

