// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment;

public interface ProductsListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.ProductsList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 product_id = 1;</code>
   * @return A list containing the productId.
   */
  java.util.List<java.lang.Integer> getProductIdList();
  /**
   * <code>repeated int32 product_id = 1;</code>
   * @return The count of productId.
   */
  int getProductIdCount();
  /**
   * <code>repeated int32 product_id = 1;</code>
   * @param index The index of the element to return.
   * @return The productId at the given index.
   */
  int getProductId(int index);
}
