// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 registration_id = 1;</code>
   * @return The registrationId.
   */
  int getRegistrationId();

  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  java.util.List<dk.via.sdj3.assignment.Animal> 
      getAnimalList();
  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  dk.via.sdj3.assignment.Animal getAnimal(int index);
  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  int getAnimalCount();
  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  java.util.List<? extends dk.via.sdj3.assignment.AnimalOrBuilder> 
      getAnimalOrBuilderList();
  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  dk.via.sdj3.assignment.AnimalOrBuilder getAnimalOrBuilder(
      int index);
}
