// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment;

/**
 * Protobuf type {@code slaughterhouse.Product}
 */
public final class Product extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:slaughterhouse.Product)
    ProductOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Product.newBuilder() to construct.
  private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Product() {
    animal_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Product();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Product(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            registrationId_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              animal_ = new java.util.ArrayList<dk.via.sdj3.assignment.Animal>();
              mutable_bitField0_ |= 0x00000001;
            }
            animal_.add(
                input.readMessage(dk.via.sdj3.assignment.Animal.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        animal_ = java.util.Collections.unmodifiableList(animal_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Product_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Product_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.sdj3.assignment.Product.class, dk.via.sdj3.assignment.Product.Builder.class);
  }

  public static final int REGISTRATION_ID_FIELD_NUMBER = 1;
  private int registrationId_;
  /**
   * <code>int32 registration_id = 1;</code>
   * @return The registrationId.
   */
  @java.lang.Override
  public int getRegistrationId() {
    return registrationId_;
  }

  public static final int ANIMAL_FIELD_NUMBER = 2;
  private java.util.List<dk.via.sdj3.assignment.Animal> animal_;
  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  @java.lang.Override
  public java.util.List<dk.via.sdj3.assignment.Animal> getAnimalList() {
    return animal_;
  }
  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dk.via.sdj3.assignment.AnimalOrBuilder> 
      getAnimalOrBuilderList() {
    return animal_;
  }
  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  @java.lang.Override
  public int getAnimalCount() {
    return animal_.size();
  }
  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  @java.lang.Override
  public dk.via.sdj3.assignment.Animal getAnimal(int index) {
    return animal_.get(index);
  }
  /**
   * <code>repeated .slaughterhouse.Animal animal = 2;</code>
   */
  @java.lang.Override
  public dk.via.sdj3.assignment.AnimalOrBuilder getAnimalOrBuilder(
      int index) {
    return animal_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (registrationId_ != 0) {
      output.writeInt32(1, registrationId_);
    }
    for (int i = 0; i < animal_.size(); i++) {
      output.writeMessage(2, animal_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (registrationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, registrationId_);
    }
    for (int i = 0; i < animal_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, animal_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.sdj3.assignment.Product)) {
      return super.equals(obj);
    }
    dk.via.sdj3.assignment.Product other = (dk.via.sdj3.assignment.Product) obj;

    if (getRegistrationId()
        != other.getRegistrationId()) return false;
    if (!getAnimalList()
        .equals(other.getAnimalList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REGISTRATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRegistrationId();
    if (getAnimalCount() > 0) {
      hash = (37 * hash) + ANIMAL_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.sdj3.assignment.Product parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.Product parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Product parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.Product parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Product parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.sdj3.assignment.Product parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Product parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.Product parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Product parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.Product parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.sdj3.assignment.Product parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.sdj3.assignment.Product parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.sdj3.assignment.Product prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code slaughterhouse.Product}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:slaughterhouse.Product)
      dk.via.sdj3.assignment.ProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.sdj3.assignment.Product.class, dk.via.sdj3.assignment.Product.Builder.class);
    }

    // Construct using dk.via.sdj3.assignment.Product.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnimalFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      registrationId_ = 0;

      if (animalBuilder_ == null) {
        animal_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        animalBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.sdj3.assignment.Slaughterhouse.internal_static_slaughterhouse_Product_descriptor;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.Product getDefaultInstanceForType() {
      return dk.via.sdj3.assignment.Product.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.Product build() {
      dk.via.sdj3.assignment.Product result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.sdj3.assignment.Product buildPartial() {
      dk.via.sdj3.assignment.Product result = new dk.via.sdj3.assignment.Product(this);
      int from_bitField0_ = bitField0_;
      result.registrationId_ = registrationId_;
      if (animalBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          animal_ = java.util.Collections.unmodifiableList(animal_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.animal_ = animal_;
      } else {
        result.animal_ = animalBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.sdj3.assignment.Product) {
        return mergeFrom((dk.via.sdj3.assignment.Product)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.sdj3.assignment.Product other) {
      if (other == dk.via.sdj3.assignment.Product.getDefaultInstance()) return this;
      if (other.getRegistrationId() != 0) {
        setRegistrationId(other.getRegistrationId());
      }
      if (animalBuilder_ == null) {
        if (!other.animal_.isEmpty()) {
          if (animal_.isEmpty()) {
            animal_ = other.animal_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnimalIsMutable();
            animal_.addAll(other.animal_);
          }
          onChanged();
        }
      } else {
        if (!other.animal_.isEmpty()) {
          if (animalBuilder_.isEmpty()) {
            animalBuilder_.dispose();
            animalBuilder_ = null;
            animal_ = other.animal_;
            bitField0_ = (bitField0_ & ~0x00000001);
            animalBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnimalFieldBuilder() : null;
          } else {
            animalBuilder_.addAllMessages(other.animal_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.sdj3.assignment.Product parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.sdj3.assignment.Product) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int registrationId_ ;
    /**
     * <code>int32 registration_id = 1;</code>
     * @return The registrationId.
     */
    @java.lang.Override
    public int getRegistrationId() {
      return registrationId_;
    }
    /**
     * <code>int32 registration_id = 1;</code>
     * @param value The registrationId to set.
     * @return This builder for chaining.
     */
    public Builder setRegistrationId(int value) {
      
      registrationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 registration_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistrationId() {
      
      registrationId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<dk.via.sdj3.assignment.Animal> animal_ =
      java.util.Collections.emptyList();
    private void ensureAnimalIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        animal_ = new java.util.ArrayList<dk.via.sdj3.assignment.Animal>(animal_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.sdj3.assignment.Animal, dk.via.sdj3.assignment.Animal.Builder, dk.via.sdj3.assignment.AnimalOrBuilder> animalBuilder_;

    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public java.util.List<dk.via.sdj3.assignment.Animal> getAnimalList() {
      if (animalBuilder_ == null) {
        return java.util.Collections.unmodifiableList(animal_);
      } else {
        return animalBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public int getAnimalCount() {
      if (animalBuilder_ == null) {
        return animal_.size();
      } else {
        return animalBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public dk.via.sdj3.assignment.Animal getAnimal(int index) {
      if (animalBuilder_ == null) {
        return animal_.get(index);
      } else {
        return animalBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public Builder setAnimal(
        int index, dk.via.sdj3.assignment.Animal value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalIsMutable();
        animal_.set(index, value);
        onChanged();
      } else {
        animalBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public Builder setAnimal(
        int index, dk.via.sdj3.assignment.Animal.Builder builderForValue) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        animal_.set(index, builderForValue.build());
        onChanged();
      } else {
        animalBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public Builder addAnimal(dk.via.sdj3.assignment.Animal value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalIsMutable();
        animal_.add(value);
        onChanged();
      } else {
        animalBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public Builder addAnimal(
        int index, dk.via.sdj3.assignment.Animal value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalIsMutable();
        animal_.add(index, value);
        onChanged();
      } else {
        animalBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public Builder addAnimal(
        dk.via.sdj3.assignment.Animal.Builder builderForValue) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        animal_.add(builderForValue.build());
        onChanged();
      } else {
        animalBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public Builder addAnimal(
        int index, dk.via.sdj3.assignment.Animal.Builder builderForValue) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        animal_.add(index, builderForValue.build());
        onChanged();
      } else {
        animalBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public Builder addAllAnimal(
        java.lang.Iterable<? extends dk.via.sdj3.assignment.Animal> values) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, animal_);
        onChanged();
      } else {
        animalBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public Builder clearAnimal() {
      if (animalBuilder_ == null) {
        animal_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        animalBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public Builder removeAnimal(int index) {
      if (animalBuilder_ == null) {
        ensureAnimalIsMutable();
        animal_.remove(index);
        onChanged();
      } else {
        animalBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public dk.via.sdj3.assignment.Animal.Builder getAnimalBuilder(
        int index) {
      return getAnimalFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public dk.via.sdj3.assignment.AnimalOrBuilder getAnimalOrBuilder(
        int index) {
      if (animalBuilder_ == null) {
        return animal_.get(index);  } else {
        return animalBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public java.util.List<? extends dk.via.sdj3.assignment.AnimalOrBuilder> 
         getAnimalOrBuilderList() {
      if (animalBuilder_ != null) {
        return animalBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(animal_);
      }
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public dk.via.sdj3.assignment.Animal.Builder addAnimalBuilder() {
      return getAnimalFieldBuilder().addBuilder(
          dk.via.sdj3.assignment.Animal.getDefaultInstance());
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public dk.via.sdj3.assignment.Animal.Builder addAnimalBuilder(
        int index) {
      return getAnimalFieldBuilder().addBuilder(
          index, dk.via.sdj3.assignment.Animal.getDefaultInstance());
    }
    /**
     * <code>repeated .slaughterhouse.Animal animal = 2;</code>
     */
    public java.util.List<dk.via.sdj3.assignment.Animal.Builder> 
         getAnimalBuilderList() {
      return getAnimalFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.sdj3.assignment.Animal, dk.via.sdj3.assignment.Animal.Builder, dk.via.sdj3.assignment.AnimalOrBuilder> 
        getAnimalFieldBuilder() {
      if (animalBuilder_ == null) {
        animalBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dk.via.sdj3.assignment.Animal, dk.via.sdj3.assignment.Animal.Builder, dk.via.sdj3.assignment.AnimalOrBuilder>(
                animal_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        animal_ = null;
      }
      return animalBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:slaughterhouse.Product)
  }

  // @@protoc_insertion_point(class_scope:slaughterhouse.Product)
  private static final dk.via.sdj3.assignment.Product DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.sdj3.assignment.Product();
  }

  public static dk.via.sdj3.assignment.Product getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Product>
      PARSER = new com.google.protobuf.AbstractParser<Product>() {
    @java.lang.Override
    public Product parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Product(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Product> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Product> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.sdj3.assignment.Product getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

