// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package dk.via.sdj3.assignment;

public final class Slaughterhouse {
  private Slaughterhouse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_IdQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_IdQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_AnimalList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_AnimalList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_ProductsList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_ProductsList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_Animal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_Animal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024slaughterhouse.proto\022\016slaughterhouse\"\025" +
      "\n\007IdQuery\022\n\n\002id\030\001 \001(\005\"\037\n\nAnimalList\022\021\n\ta" +
      "nimal_id\030\001 \003(\005\"\"\n\014ProductsList\022\022\n\nproduc" +
      "t_id\030\001 \003(\005\"N\n\006Animal\022\027\n\017registration_id\030" +
      "\001 \001(\005\022+\n\nproduct_id\030\002 \001(\0132\027.slaughterhou" +
      "se.Product\"J\n\007Product\022\027\n\017registration_id" +
      "\030\001 \001(\005\022&\n\006animal\030\002 \003(\0132\026.slaughterhouse." +
      "Animal2\255\001\n\016SlaughterHouse\022L\n\023getAnimalsI" +
      "nProduct\022\027.slaughterhouse.IdQuery\032\032.slau" +
      "ghterhouse.AnimalList\"\000\022M\n\022whereAnimalHa" +
      "sBeen\022\027.slaughterhouse.IdQuery\032\034.slaught" +
      "erhouse.ProductsList\"\000B\032\n\026dk.via.sdj3.as" +
      "signmentP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_slaughterhouse_IdQuery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_slaughterhouse_IdQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_IdQuery_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_slaughterhouse_AnimalList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_slaughterhouse_AnimalList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_AnimalList_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_slaughterhouse_ProductsList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_slaughterhouse_ProductsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_ProductsList_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_slaughterhouse_Animal_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_slaughterhouse_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_Animal_descriptor,
        new java.lang.String[] { "RegistrationId", "ProductId", });
    internal_static_slaughterhouse_Product_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_slaughterhouse_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_Product_descriptor,
        new java.lang.String[] { "RegistrationId", "Animal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
